CLIENT_ID = "potato-launcher"
CLIENT_SECRET = "ui5ULhQlactyntldzSk6JAeUZfA-aVej_XAeu_BIQPTihzEJdsjpfaxH5yGKbN0A"
SERVER_BASE = "https://mc.petr1furious.me/"
LAUNCHER_NAME = "potato_launcher"
APP_NAME = "potato_launcher"
