CLIENT_ID = "dvasmp1"
CLIENT_SECRET = "ICLLyGfzhLCyHhAiH5kmcL4QOt7N7RNrQbDkrUE1kB5GOu_EPo503iz3nsiZ34mq"
SERVER_BASE = "https://mc.vanutp.dev/"
LAUNCHER_NAME = "dva_smp_launcher"
APP_NAME = "dva_smp_launcher"
