import { VerticalBox } from "std-widgets.slint";
import { PageLoading } from "page_loading.slint";
import { PageError } from "page_error.slint";
import { PageAuthWaiting } from "page_auth_waiting.slint";
import { PageConfig } from "page_config.slint";
import { PageStarting } from "page_starting.slint";

export component AppWindow inherits Window {
    in property<int> page: 0;
    in property<string> error: "";

    in property<string> username;
    in-out property<string> memory;
    callback memory-changed;
    callback start;

    in property<string> starting-status;
    in property<float> starting-progress;

    title: "DVA SMP Launcher";

    VerticalBox {
        if page == 0 : PageLoading {}
        if page == 1 : PageError { error: error; }
        if page == 2 : PageAuthWaiting {}
        if page == 3 : config := PageConfig {
            username: root.username;
            memory: root.memory;
            memory-changed => {
                root.memory = config.memory;
                root.memory-changed()
            }
            start => {
                root.start()
            }
        }
        if page == 4 : PageStarting {
            status: root.starting-status;
            progress: root.starting-progress;
        }
    }
}
