import { VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component PageConfig inherits VerticalBox {
    in property<string> username;
    in-out property<string> memory <=> mem-edit.text;
    callback memory-changed;
    in-out property<string> java-path <=> java-path-edit.text;
    callback java-path-changed;
    callback start;

    height: 130px;
    width: 100%;
    Text {
        text: "Вы вошли как " + username;
    }
    Text {
        text: "Выделенная память:";
    }
    mem-edit := LineEdit {
        width: 100%;
        edited(text) => {
            root.memory = text;
            root.memory-changed()
        }
    }
    Text {
        text: "Путь к jabe:";
    }
    java-path-edit := LineEdit {
        width: 100%;
        edited(text) => {
            root.java-path = text;
            root.java-path-changed()
        }
    }

    Button {
        text: "Запустить!";
        clicked => {
            root.start()
        }
    }
}
